name:                paso
version:             0.1.0.0
github:              "anqurvanillapy/paso"
license:             MIT
author:              "AnqurVanillapy"
maintainer:          "anqurvanillapy@gmail.com"
copyright:           "2018 AnqurVanillapy"

extra-source-files:
- README.md

synopsis:            A dependently-typed programming language
category:            Language

description:         A dependently-typed programming language

dependencies:
- base >= 4.8 && < 5

library:
  source-dirs: src

executables:
  paso:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paso

tests:
  paso-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - paso
